name: Publish Github Action
run-name: ${{ github.actor }} is publishing the website
on: [push]
jobs:
  Publish-Website-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Building production bundle and uploading via FTP."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
        
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: run build # will run `yarn run build` command

      - name: Generate sitemap.txt
        uses: borales/actions-yarn@v4
        with:
          cmd: run generate-sitemap # will run `yarn generate-sitemap` command
      
      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: oli.show/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            package.json
            README.md
            tsconfig.json
            webpack.config.js
            yarn.lock

      - run: echo "This job's status is ${{ job.status }}."